datasource:
  host: "127.0.0.1"
  port: 3306
  username: "root"
  password: ""
  poolSize: 50

debug:
  enabled: false

plunder:
  generated-structures:
    enabled: true
    world-whitelist:
      - "world"
    structure-blacklist:
  invincible: true

messages:
  broadcast-restock:
    enabled: true
  plunder:
    title: "&5Plunder"
  