name: GoblinsPlunder
version: 0.1.0
main: com.levthedev.mc.GoblinsPlunder
description: A simple Spigot plugin example

api-version: '1.20'

commands:
  gp:
    description: Goblins Plunder
    usage: /gp
    aliases: [goblinsplunder]
