name: GoblinsPlunder
version: 1.1.1
main: com.levthedev.mc.GoblinsPlunder
description: A simple Spigot plugin example

api-version: '1.18'
commands:
  gp:
    description: Goblins Plunder
    usage: /gp
    aliases: [goblinsplunder, plunder]
permissions:
  goblinsplunder.admin:
    description: Required to use the gp commands, also bypasses invincibility
    default: op