name: GoblinsPlunder
version: 1.1.0
main: com.levthedev.mc.GoblinsPlunder
description: A simple Spigot plugin example

api-version: '1.18'
commands:
  gp:
    description: Goblins Plunder
    usage: /gp
    aliases: [goblinsplunder, plunder]
permissions:
  goblinsplunder.admin:
    decription: Allows full use of the plugin
    default: op