name: GoblinsPlunder
version: 0.2.0
main: com.levthedev.mc.GoblinsPlunder
description: A simple Spigot plugin example

api-version: '1.18'
commands:
  gp:
    description: Goblins Plunder
    usage: /gp
    aliases: [goblinsplunder, plunder]
